### ISSUE TITLE
Installing TIMAC Fw?

### ISSUE THREAD

**Issue by DL5SMB** [danielkucera/epaper-station#7]
Hi Daniel,

maybe this is a stupid question, but how do I get the TIMAC firmware on the CC2531?

I downloaded the TIMAC package, installed the software, but I can't see a special firmnware within the package to upload on the stick? 

And the next question would be: Do i need a CC debugger for this?

Sascha

**Comment by danielkucera** [comment]
Hi,

it's in this folder after install:
![20220813_070506](https://user-images.githubusercontent.com/1734256/184469490-7287bd56-6ff9-4716-8b1d-2c8783fb2065.jpg)

Then you can follow this guide:
https://www.zigbee2mqtt.io/guide/adapters/flashing/alternative_flashing_methods.html

**Comment by DL5SMB** [comment]
Thanks alot - awesome. 👍
I would not have found this on my own.

**Comment by pklosko** [comment]
Short HowTo in CZ lang : https://www.klosko.net/blog/=clanek=epaper-samsung-solum4-2
